name: Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install zensical git+https://github.com/squidfunk/mike.git
      - run: bash scripts/pull_from_repos.sh
      - run: python scripts/gen_ref_pages.py
      - run: zensical build --clean
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          mike deploy --push --update-aliases latest
        id: deployment